sudo: required
services:
- docker
language: generic
script:
- docker build -t quorauk/discordbot .
after_success:
- docker tag quorauk/discordbot:latest quourauk/discordbot:$TRAVIS_BUILD_NUMBER 
- docker tag quorauk/discordbot:latest quourauk/discordbot:$TRAVIS_COMMIT
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push quorauk/discordbot
