sudo: required
services:
- docker
language: generic
addons:
  ssh_known_hosts:
  - "$SERVER"
before_script:
  - echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- docker build -t quorauk/discordbot .
after_success:
- docker tag quorauk/discordbot:latest quorauk/discordbot:$TRAVIS_BUILD_NUMBER
- docker tag quorauk/discordbot:latest quorauk/discordbot:$TRAVIS_COMMIT
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push quorauk/discordbot
before_install:
- openssl aes-256-cbc -K $encrypted_d8f043273547_key -iv $encrypted_d8f043273547_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: ssh -p22 $SERVER_USER@$SERVER "cd discordbot && docker-compose pull && docker-compose down && docker-compose up -d"
  on:
    branch: master
