version: "3"
services:
  discord:
    image: quorauk/discordbot:latest
    restart: always
    links:
    - db
    env_file:
    - .env
  db:
    image: postgres:10.2
    ports:
    - 5432:5432
    volumes:
       - serverdb:/var/lib/postgresql/data
    restart: always
volumes:
  serverdb:
